version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.NPM_REGISTRY_REGISTRY_GH_ORG_TOKEN}}
updates:
- package-ecosystem: npm
  registries:
    - npm-github
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  commit-message:
    prefix: chore
    include: scope
  ignore:
    - dependency-name: 'framer-motion'
      versions:
        - '>=8.0.0'
  groups:
    production-dependencies:
      applies-to: version-updates
      dependency-type: production
      update-types:
        - minor
        - patch
      patterns:
        - '*'
    dev-dependencies:
      applies-to: version-updates
      dependency-type: development
      update-types:
        - minor
        - patch
      patterns:
        - '*'