version: 2.1

jobs:
  all:
    docker:
      - image: cypress/browsers:node8.15.1-chrome73
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v2-deps-{{ .Branch }}-
            - v2-deps-
      - run: npm ci
      - save_cache:
          key: v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run: npm run lint
      - run: npm test
      - run: npm run build
      - run: npm run size
      - run: npm run integration
      - store_test_results:
          path: test/cypress/reports
      - store_artifacts:
          path: test/cypress/screenshots

workflows:
  version: 2
  # run on every commit
  commit:
    jobs:
      - all
  # run in master every hour, 0:40, 1:40...
  schedule:
    jobs:
      - all
    triggers:
      - schedule:
          cron: '40 * * * *'
          filters:
            branches:
              only:
                - master
