version: 2.1

jobs:
  unit:
    docker:
      - image: cimg/node:16.13.2
        environment:
          ## this enables colors in the output
          TERM: xterm
    steps:
      - checkout
      - run: npm ci
      - run: npm run lint
      - run: npm test
      - run: npm run build
      - run: npm run size
      - store_test_results:
          path: test/unit/reports

  semantic-release:
    docker:
      - image: cimg/node:16.13.2
    steps:
      - checkout
      - run:
          name: Setup NPM
          command: |
            echo $'@contentful:registry=https://registry.npmjs.org/
            //registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> ~/.npmrc
      - run: npm ci
      - run:
          name: Releasing
          command: npm run semantic-release

workflows:
  version: 2
  # run on every commit
  commit:
    jobs:
      - unit
      - semantic-release:
          requires:
            - unit
          filters:
            branches:
              only:
                - master
                - canary
