version: 2.1

orbs:
  vault: contentful/vault@1

jobs:
  unit:
    docker:
      - image: cimg/node:16.13.2
        environment:
          ## this enables colors in the output
          TERM: xterm
    steps:
      - checkout
      - run:
          name: Npm Install
          command: npm ci
      - run:
          name: Run linter
          command: npm run lint
      - run:
          name: Run test
          command: npm test
      - run:
          name: Building
          command: npm run build
      - run:
          name: Sizing
          command: npm run size
      - store_test_results:
          path: test/unit/reports

  semantic-release:
    docker:
      - image: cimg/node:16.13.2
    steps:
      - checkout
      - vault/get-secrets:
          template-preset: "semantic-release"
      - run:
          name: Setup NPM
          command: |
            echo $'@contentful:registry=https://registry.npmjs.org/
            //registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> ~/.npmrc
      - run: npm ci
      - run:
          name: Releasing
          command: npm run semantic-release

workflows:
  version: 2
  # run on every commit
  commit:
    jobs:
      - unit:
          context:
            - vault
      - semantic-release:
          context:
            - vault
          requires:
            - unit
          filters:
            branches:
              only:
                - master
                - canary
