version: 2.1

cache-key: &cache-key
  key: dependency-cache-primary-{{ arch }}-{{ checksum ".nvmrc" }}-{{ checksum "package-lock.json" }}

jobs:
  all:
    docker:
      - image: cypress/browsers:node8.15.1-chrome73
    steps:
      - checkout
      - restore_cache: *cache-key
      - run: npm ci
      - run:
          name: Reverting "package-lock.json"
          # `npm install` can modify `package-lock.json`. If it happens, we're caching dependencies
          # with a wrong key. To mitigate this problem we restore the original lock file.
          command: git checkout -- package-lock.json
      - save_cache:
          <<: *cache-key
          paths:
            - ./node_modules
      - run: npm run lint
      - run: npm test
      - run: npm run build
      - run: npm run size
      - run:
          name: npm run integration
          command: |
            set -e
            npm run integration
      - store_test_results:
          path: test/cypress/reports
      - store_artifacts:
          path: test/cypress/screenshots

workflows:
  version: 2
  # run on every commit
  commit:
    jobs:
      - all
  # run in master every hour, 0:40, 1:40...
  schedule:
    jobs:
      - all
    triggers:
      - schedule:
          cron: '40 * * * *'
          filters:
            branches:
              only:
                - master
